version: '3.8'

services:
  # Laravel App Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./:/var/www
    networks:
      - app-network
    depends_on:
      - db
      - redis

  # Nginx Service
  nginx:
    image: nginx:alpine
    container_name: nginx
    restart: unless-stopped
    ports:
      - "8000:80"  # Truy cập Laravel qua http://localhost:8000
    volumes:
      - ./:/var/www
      - ./docker/nginx.conf:/etc/nginx/conf.d/default.conf
    networks:
      - app-network
    depends_on:
      - app

  # MySQL Service
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: Admin123@        # 🔑 Mật khẩu root
      MYSQL_DATABASE: product_api         # 📘 Tên database
      MYSQL_ROOT_HOST: '%'                # 🔓 Cho phép truy cập từ container khác
    volumes:
      - db-data:/var/lib/mysql
    ports:
      - "3307:3306"                       # Host:Container
    networks:
      - app-network

  # Redis Service
  redis:
    image: redis:alpine
    container_name: redis
    restart: unless-stopped
    ports:
      - "6379:6379"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db-data:
    driver: local
